const elementsToRemove = [
  "script",
  "style",
  "meta",
  "link",
  "noscript",
  "head",
  "iframe",
  "footer",
  "img",
  "svg",
  "path",
  "nav",
  "form",
];

// Map elements to their ARIA roles
const elementsToMapWithAriaRoles = {
  a: "link",
  ul: "list",
  li: "listitem",
  article: "article",
  aside: "complementary",
  body: "document",
  button: "button",
  datalist: "listbox",
  details: "group",
  dialog: "dialog",
  fieldset: "group",
  footer: "contentinfo",
  form: "form",
  header: "banner",
  input: "textbox",
  main: "main",
  nav: "navigation",
  option: "option",
  output: "status",
  progress: "progressbar",
  section: "region",
  select: "listbox",
  textarea: "textbox",
};

// Remove uninteresting attributes
const attributesToRemove = [
  "class",
  "id",
  "style",
  "onclick",
  "ondblclick",
  "onchange",
  "onmousedown",
  "onmouseup",
  "onmouseover",
  "onmouseout",
  "onkeypress",
  "onkeydown",
  "onkeyup",
  "onfocus",
  "onblur",
  "onreset",
  "onload",
  "onunload",
  "onsubmit",
  "onselect",
  "onerror",
  "onabort",
  "onresize",
  "onscroll",
  "oncontextmenu",
  "oninput",
  "oninvalid",
  "onsearch",
  "onbeforeunload",
  "popover",
  "for",
];

module.exports = {
  elementsToRemove,
  elementsToMapWithAriaRoles,
  attributesToRemove,
};
